//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCEntities : DbContext
    {
        public MVCEntities()
            : base("name=MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Backend> Backends { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Frontend> Frontends { get; set; }
        public virtual DbSet<Mobility> Mobilities { get; set; }
        public virtual DbSet<Testing> Testings { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
